import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../../styles/Home.module.css'
import Characters from '../components/characters/characters'
import Header from '../components/header'
import { ICharacter } from '../interfaces/characters'
import getWorks from '../lib/work'

export async function getServerSideProps() {
  const charactersRes = await getWorks()
  const characters = charactersRes?.data?.results

  return {
    props: {
      characters,
    },
  }
}

function Home({ characters }: { characters: ICharacter[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello World!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Header />
        <h1 className={styles.title}>Hello World!</h1>
        <Characters characters={characters} />
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
